logging:
  level:
    root: INFO
    com:
      course-management: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
            sql.BasicBinder: TRACE
      springframework:
        web: DEBUG
        security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8062
jwt:
  secret: mensenisevdimgullericindesenmeneyoxdedinqaldiicimde
spring:
  mvc:
    log-request-details: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
        format_sql: true

  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://ep-noisy-hall-a2ra9lfz-pooler.eu-central-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_po8GJI4XMORL
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false
    contexts: dev
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  paths-to-match: /**